TicketSystem/TicketSystem.Web/Controllers/BandsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using TicketSystem.Common.Contstants;
using TicketSystem.Services.Normal.Contracts;
using TicketSystem.Services.Normal.Models.Bands;

namespace TicketSystem.Web.Controllers
{
    public class BandsController : Controller
    {
        private readonly IBandService bandService;
        private readonly IMemoryCache cache;

        public BandsController( IBandService bandService, IMemoryCache cache )
        {
            this.bandService = bandService;
            this.cache = cache;
        }

        public async Task< IActionResult > Index()
        {
            var value =  await this.bandService.AllAsync();

            return this.View( value );
        }

        public async Task< IActionResult > Details( int id )
        {
            if ( id <= 0 )
            {
                this.ModelState.AddModelError( "", "Invalid Id." );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.BadRequest();
            }
            var value = await this.bandService.DetailsAsync( id );

            return this.View( value );
        }

        public async Task< IActionResult > AlbumDetails( int id )
        {
            if ( id <= 0 )
            {
                this.ModelState.AddModelError( "", "Invalid id" );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.BadRequest();
            }
            var value = await this.bandService.AlbumDetailsAsync( id );

            return this.View( value );
        }

        public IActionResult AlbumByTrack( int id )
        {
            var album = this.bandService.GetAlbumDetailsByTrackAsync( id );

            return this.View( "AlbumDetails", album );
        }
    }
}

TicketSystem/TicketSystem.Web/Controllers/ConcertsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TicketSystem.Services.Normal.Contracts;
using TicketSystem.Web.Models;

namespace TicketSystem.Web.Controllers
{
    public class ConcertsController : Controller
    {
        private readonly IConcertService concertService;
        private readonly IUserService userService;

        public ConcertsController( IConcertService concertService, IUserService userService )
        {
            this.concertService = concertService;
            this.userService = userService;
        }

        public async Task< IActionResult > Details( int id )
        {
            if ( id <= 0 )
            {
                this.ModelState.AddModelError( "", "Invalid Id" );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.BadRequest();
            }

            var concert = await this.concertService.DetailsAsync( id );
            var comments = await this.userService.AllCommentsForConcertAsync( id );

            return this.View( new ConcertDetailsViewModel
            {
                Concert = concert,
                Comments = comments
            } );
        }

        public async Task< IActionResult > Index()
        {
            var concerts = await this.concertService.IndexAsync();

            return this.View( concerts );
        }
    }
}

TicketSystem/TicketSystem.Web/Views/Shared/_Layout.cshtml
@using TicketSystem.Common.Contstants
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@( this.ViewData[ "Title" ] ) - Music Town</title>

    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.0.12/css/all.css"
          integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="~/js/site.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <link rel="stylesheet" href="~/css/site.css" />
    <link type="text/css" href="~/css/AdminLayout.css" rel="stylesheet" />
    <link type="text/css" href="~/css/NormalUsers.css" rel="stylesheet" />

</head>
<body class="MetalFont">
    @if ( this.TempData.ContainsKey( WebConstants.TempDataSuccessMessageKey ) )
    {
        <div class="alert alert-success text-center alert-dismissable m-auto" style="width: 33%">
            @( this.TempData[ WebConstants.TempDataSuccessMessageKey ] ) <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    @if ( this.TempData.ContainsKey( WebConstants.TempDataErrorMessageKey ) )
    {
        <div class="alert alert-danger text-center alert-dismissable m-auto" style="width: 33%">
            @( this.TempData[ WebConstants.TempDataErrorMessageKey ] ) <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }


    <nav class="navbar navbar-expand-lg fixed-top w-100" style="background: black;">
        <div class="container-fluid">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Music Town</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar-items" aria-controls="navbar-items" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars" style="color:goldenrod"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbar-items">
                <div class="navbar-nav ml-lg-5 ml-sm-auto text-center">

                    <div class="nav-item dropdown">
                        <a data-toggle="dropdown" class="nav-link" onclick="toggleHelpBars('toggle')">
                            <i class="fa fa-search"></i> Search
                        </a>
                        <div class="dropdown-menu nav-item-custm to-be-toggled" id="toggle">

                            <form class="form-inline offset-lg-0 offset-sm-4" role="search" asp-area="" asp-controller="Home" asp-action="Search" id="search-form" method="get">
                                <div class="col-lg-6 col-sm-3 pl-0" style="color: goldenrod !important">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="checkbox" name="songs" id="songs" value="false" onclick="changeCheckedValue(id)" />Songs
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="checkbox" name="albums" id="albums" value="false" onclick="changeCheckedValue(id)" />Albums
                                        </label>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-sm-3 pl-0">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="checkbox" name="bands" id="bands" value="false" onclick="changeCheckedValue(id)" />Bands
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="checkbox" name="concerts" id="concerts" value="false" onclick="changeCheckedValue(id)" />Concerts
                                        </label>
                                    </div>
                                </div>
                                <div class="col-lg-12 px-0 pt-1">
                                    <div class="input-group" style="width: 250px">
                                        <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="searchTerm" id="searchTerm">
                                        <div class="input-group-append">
                                            <button class="btn" type="submit" id="search-btn">Search</button>
                                        </div>
                                    </div>
                                </div>

                            </form>

                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a data-toggle="dropdown" class="nav-link dropdown-toggle" onclick="toggleHelpBars('browse')">Browse</a>
                        <div class="dropdown-menu nav-item-custm to-be-toggled" id="browse">
                            <a asp-area="" class="dropdown-item text-sm-center text-lg-left" asp-controller="Bands" asp-action="Index">Browse Bands</a>
                            <a asp-area="" class="dropdown-item text-sm-center text-lg-left" asp-controller="Concerts" asp-action="Index">Browse Concerts</a>
                        </div>
                    </div>
                    @if ( this.User.IsInRole( WebConstants.AdminRole ) )
                    {
                        <a asp-area="Admin" asp-controller="UsersAdmin" asp-action="AdminPanel" class="nav-link nav-item">Admin Panel</a>
                    }
                    @if ( this.User.IsInRole( WebConstants.OrganizerRole ) && !this.User.IsInRole( WebConstants.AdminRole ) )
                    {
                        <div class="nav-item dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle nav-link" onclick="toggleHelpBars('org')">Concerts <span class="caret"></span></a>
                            <div class="dropdown-menu nav-item-custm to-be-toggled" id="org">
                                <a asp-area="Organizer" class="dropdown-item" asp-controller="Organizer" asp-action="Create">Create Concert</a>
                                <a asp-area="Organizer" class="dropdown-item" asp-controller="Organizer" asp-action="Index">All Concerts</a>
                            </div>
                        </div>
                    }
                </div>
                @await this.Html.PartialAsync( "_LoginPartial" )
            </div>
        </div>
    </nav>
    <main class="container">
        @( this.RenderBody() )
    </main>
    <footer>
        <div id="footer-div-1">
            <p>&copy; 2018 - Music Town</p>
        </div>
        <div id="footer-div-2">
            <ul>
                <li><a href="" id="facebook"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="" id="twitter"><i class="fab fa-twitter"></i></a></li>
                <li><a href="" id="instagram"><i class="fab fa-instagram"></i></a></li>
            </ul>
        </div>
    </footer>
    @( this.RenderSection( "Scripts", required: false ) )
</body>
</html>