TicketSystem/TicketSystem.Web/Areas/Organizer/Models/Concerts/CreateConcertViewModel.cs
using System.Collections.Generic;
using TicketSystem.Services.Organizer.Models;

namespace TicketSystem.Web.Areas.Organizer.Models.Concerts
{
    public class CreateConcertViewModel
    {
        public CreateConcertServiceModel ConcertServiceModel { get; set; }

        public List<GetBandsServiceModel> Bands { get; set; }
    }
}

TicketSystem/TicketSystem.Web/Controllers/BandsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using TicketSystem.Common.Contstants;
using TicketSystem.Services.Normal.Contracts;
using TicketSystem.Services.Normal.Models.Bands;

namespace TicketSystem.Web.Controllers
{
    public class BandsController : Controller
    {
        private readonly IBandService bandService;
        private readonly IMemoryCache cache;

        public BandsController( IBandService bandService, IMemoryCache cache )
        {
            this.bandService = bandService;
            this.cache = cache;
        }

        public async Task< IActionResult > Index()
        {
            var value =  await this.bandService.AllAsync();

            return this.View( value );
        }

        public async Task< IActionResult > Details( int id )
        {
            if ( id <= 0 )
            {
                this.ModelState.AddModelError( "", "Invalid Id." );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.BadRequest();
            }
            var value = await this.bandService.DetailsAsync( id );

            return this.View( value );
        }

        public async Task< IActionResult > AlbumDetails( int id )
        {
            if ( id <= 0 )
            {
                this.ModelState.AddModelError( "", "Invalid id" );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.BadRequest();
            }
            var value = await this.bandService.AlbumDetailsAsync( id );

            return this.View( value );
        }

        public IActionResult AlbumByTrack( int id )
        {
            var album = this.bandService.GetAlbumDetailsByTrackAsync( id );

            return this.View( "AlbumDetails", album );
        }
    }
}

TicketSystem/TicketSystem.Web/Controllers/ConcertsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TicketSystem.Services.Normal.Contracts;
using TicketSystem.Web.Models;

namespace TicketSystem.Web.Controllers
{
    public class ConcertsController : Controller
    {
        private readonly IConcertService concertService;
        private readonly IUserService userService;

        public ConcertsController( IConcertService concertService, IUserService userService )
        {
            this.concertService = concertService;
            this.userService = userService;
        }

        public async Task< IActionResult > Details( int id )
        {
            if ( id <= 0 )
            {
                this.ModelState.AddModelError( "", "Invalid Id" );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.BadRequest();
            }

            var concert = await this.concertService.DetailsAsync( id );
            var comments = await this.userService.AllCommentsForConcertAsync( id );

            return this.View( new ConcertDetailsViewModel
            {
                Concert = concert,
                Comments = comments
            } );
        }

        public async Task< IActionResult > Index()
        {
            var concerts = await this.concertService.IndexAsync();

            return this.View( concerts );
        }
    }
}

TicketSystem/TicketSystem.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Ganss.XSS;
using TicketSystem.Data.Models;
using TicketSystem.Services.Normal.Contracts;
using TicketSystem.Services.Normal.Models.Users;
using TicketSystem.Web.Extensions;

namespace TicketSystem.Web.Controllers
{
    [ Authorize ]
    public class UsersController : Controller
    {
        private readonly IUserService userService;
        private readonly UserManager< User > userManager;

        public UsersController( IUserService userService, UserManager< User > userManager )
        {
            this.userService = userService;
            this.userManager = userManager;
        }

        public async Task< IActionResult > Cart()
        {
            var userId = this.userManager.GetUserId( this.User );

            var tickets = await this.userService.CartAsync( userId );

            if ( !tickets.Any() )
            {
                return this.View("EmptyCart");
            }

            return this.View( tickets );
        }

        [ HttpPost ]
        public async Task< IActionResult > AddToCart( BookTicketServiceModel ticketModel )
        {
            if ( ticketModel.ConcertId <= 0 || ticketModel.Count < 1 || ticketModel.TicketPrice == 0.0m )
            {
                this.ModelState.AddModelError( "", "Invalid Model" );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.BadRequest();
            }

            var userId = this.userManager.GetUserId( this.User );
            ticketModel.UserId = userId;

            var success = await this.userService.BookTicketAsync( ticketModel );

            if ( success )
            {
                this.TempData.AddSuccessMessage( "Ticket successfuly added to  Shopping Cart." );
                return this.RedirectToAction( "Details", "Concerts", new { id = ticketModel.ConcertId } );
            }

            return this.BadRequest();
        }

        [ HttpPost ]
        public async Task< IActionResult > Comment( CommentOnConcertServiceModel commentModel )
        {
            if ( !this.ModelState.IsValid )
            {
                return this.BadRequest();
            }

            var userId = this.userManager.GetUserId( this.User );
            commentModel.UserId = userId;

            var sanitizer = new HtmlSanitizer();
            var sanitized = sanitizer.Sanitize( commentModel.Content );

            commentModel.Content = sanitized;

            var success = await this.userService.PostCommentAsync( commentModel );

            if ( success )
            {
                return this.RedirectToAction( "Details", "Concerts", new { id = commentModel.ConcertId } );
            }

            return this.BadRequest();
        }

        public async Task< IActionResult > Checkout( string idsInput )
        {
            if ( string.IsNullOrEmpty( idsInput ) )
            {
                return this.BadRequest();
            }

            var ids = idsInput.Split( "%/%" ).Select( int.Parse ).ToList();

            if ( !ids.Any() )
            {
                this.ModelState.AddModelError( "", "Invalid Ids" );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.BadRequest();
            }

            var tickets = await this.userService.ListCheckoutAsync( ids );

            if ( !tickets.Any() )
            {
                return this.BadRequest();
            }

            return this.View( tickets );
        }

        public async Task< IActionResult > Finalize( string ids, decimal sum )
        {
            if ( string.IsNullOrEmpty( ids ) )
            {
                return this.BadRequest();
            }

            if ( sum <= 0.0m )
            {
                this.TempData.AddErrorMessage( "Incorrect amount of money!" );
                return this.RedirectToAction( nameof( this.Checkout ), new { idsInput = ids } );
            }

            var idList = ids.Split( "%/%" ).Select( int.Parse ).ToList();

            if ( !idList.Any() )
            {
                return this.BadRequest();
            }

            var sumsMatching = await this.userService.GetSumToCheckoutAsync( idList, sum );

            if ( sumsMatching )
            {
                var success = await this.userService.FinalizeOrderAsync( idList );

                if ( success )
                {
                    this.TempData.AddSuccessMessage( "Payment Successful!" );
                    return this.RedirectToAction( nameof( this.Cart ) );
                }

                this.TempData.AddErrorMessage( "Something went wrong with your order." );
                return this.RedirectToAction( nameof( this.Checkout ), new { idsInput = ids } );
            }

            this.TempData.AddErrorMessage( "Incorrect amount of money!" );

            return this.RedirectToAction( nameof( this.Checkout ), new { idsInput = ids } );
        }
    }
}

TicketSystem/TicketSystem.Web/Views/Concerts/Details.cshtml
@model ConcertDetailsViewModel

@{
    this.ViewBag.Title = this.Model.Concert.Name;
    this.Layout = "_Layout";
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>
<script>
    $("body").addClass("concert-details");
</script>

<header class="pt-5 mb-5">
    <h2 class="text-center">
        @( this.ViewData[ "Title" ] ) - @if ( this.Model.Concert.EndDate.Date < DateTime.UtcNow.Date )
        {
            <span style="color: crimson">Passed</span>
        }
        else
        {
            <span style="color: greenyellow">Upcoming</span>
        }
    </h2>
    <p class="text-center"> @( this.Model.Concert.StartDate.ToShortDateString() ) &mdash; @( this.Model.Concert.EndDate.ToShortDateString() )</p>
</header>

<div class="row mb-5">
    <div class="col-8">
        <div class="concert-details-title">
            <span>The concert took place in:</span>
            @( this.Model.Concert.Location ) - @( this.Model.Concert.City ) - @( this.Model.Concert.Country )
        </div>
        <div class="concert-details-title">
            <span>Genres:</span> @( this.Model.Concert.Genre )
        </div>
        <div class="concert-details-title">
            <span>Tickets Sold:</span>
            @( this.Model.Concert.TicketsSold )/@( this.Model.Concert.MaxNumberOfTickets )
        </div>
        <div class="concert-details-title">
            <span>Perforing Bands:</span>
            <div class="row justify-content-around">

                @for ( int i = 0; i < this.Model.Concert.Bands.Count(); i += 3 )
                {
                    var result = this.Model.Concert.Bands.Skip( i ).Take( 3 );
                    <div class="col-3">
                        @foreach ( var res in result )
                        {
                            <div class="concert-bands">
                                <a asp-area="" asp-controller="Bands" asp-action="Details" asp-route-id="@res.Id">@res.Name</a>
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
        <div class="concert-details-title">
            <span>Recording: </span>
            @if ( this.Model.Concert.StreamUrl == null )
            {
                @:No recordings yet...
            }
            else
            {
                <div id="concert-recording">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/@( this.Model.Concert.StreamUrl )" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
                </div>
            }

        </div>
    </div>
    <div class="col-4">
        <img src="@( this.Model.Concert.PosterUrl )" style="width: 300px; height: 200px" />
        <h3>Ticket Price: $@this.Model.Concert.TicketPrice</h3>
    </div>
</div>

@if ( this.User.Identity.IsAuthenticated )
{
    if ( this.Model.Concert.EndDate > DateTime.UtcNow )
    {
        <div class="row">
            <div class="col-4 offset-8">
                <form method="post" asp-area="" asp-controller="Users" asp-action="AddToCart">
                    <input type="hidden" value="@this.Model.Concert.Id" name="ConcertId" />
                    <div class="form-group">
                        <label for="Count">Number Of Tickets</label>
                        <input asp-for="@this.Model.BookTicket.Count" class="form-control" name="Count" id="Count" min="1" />
                    </div>
                    <div class="form-group">
                        <label for="TicketPrice">Sum</label>
                        <input asp-for="@this.Model.BookTicket.TicketPrice" readonly name="TicketPrice" id="TicketPrice" class="form-control" value="" style="background: rgb(220, 220, 220)" />
                    </div>
                    <input type="submit" value="Book a Ticket" class="btn btn-success Sharp" />
                </form>
            </div>
        </div>
    }

    <div class="mt-5">
        <form method="post" asp-area="" asp-controller="Users" asp-action="Comment">
            <div>
                <textarea asp-for="@this.Model.Comment.Content" id="Content" name="Content" class="form-control Sharp" placeholder="Enter Comment..."></textarea>
                <input type="hidden" value="@this.Model.Concert.Id" name="ConcertId" />
                <input type="submit" value="Comment" class="btn btn-default Sharp" />
            </div>
        </form>
    </div>
}
else
{
    <div>
        <p class="font-weight-bold">
            To book tickets or comment you must be
            <a asp-area="" asp-controller="Account" asp-action="Register" asp-route-returnUrl="@this.Context.Request.Path">registered</a>
        </p>
        <p class="font-weight-bold">
            If you already have an account please click <a asp-area="" asp-controller="Account" asp-action="Login" asp-route-returnUrl="@this.Context.Request.Path">here</a> to login.
        </p>
    </div>
}
<div class="row" style="margin-top: 50px">
    <div class="col-10 offset-1">
        <h4 class="text-center" style="color: crimson">Comments ( @this.Model.Comments.Count() ):</h4>
        @foreach ( var comment in this.Model.Comments )
        {
            <div class="concert-comments"><div>@comment.Name:</div> @this.Html.Raw( comment.Content )</div>
        }
    </div>
</div>

<script>
    $("#Count").on("keyup change", function () {
        $('#TicketPrice').val($('#Count').val() * @this.Model.Concert.TicketPrice);
    })
</script>
<script>
    $('#Content').summernote({
        placeholder: 'Hello bootstrap 4',
        tabsize: 2,
        height: 100,
        tooltip: false,
        toolbar: [
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['font', ['strikethrough', 'superscript', 'subscript']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['height', ['height']]
        ],
        disableResizeEditor: true,
        placeholder: 'Enter comment...'
    });
    $('.note-statusbar').hide();

</script>

TicketSystem/TicketSystem.Web/Views/Concerts/Index.cshtml
@model IEnumerable<IndexConcertsServiceModel>

@{
    ViewBag.Title = "Concerts";
    Layout = "_Layout";
    var half = this.Model.Count() / 2;
}
<script>
    $("body").addClass(" nu-Search");
    $('main').removeAttr('id');
</script>

<section id="concerts-index">
    <h2 class="text-center w-100 my-5">@this.ViewData[ "Title" ]</h2>
    @foreach ( var concert in this.Model.OrderBy( c => c.Name ) )
    {
        <article class="col-lg-5 concert-cell">
            <a asp-area="" asp-controller="Concerts" asp-action="Details" asp-route-id="@concert.Id">
                <span style="font-size: 20px">@concert.Name</span>
                -
                @if ( concert.EndDate < DateTime.UtcNow.Date )
                {
                    <span style="color: crimson">Passed</span>
                }
                else
                {
                    <span style="color: greenyellow">Upcoming</span>
                }
            </a>
            <p>
                <strong>@concert.StartDate.ToShortDateString()</strong> &mdash; <strong>@concert.EndDate.ToShortDateString()</strong>
            </p>
            <p>
                <em><strong>@concert.Location</strong> &mdash;  @concert.City,@concert.Country</em>
            </p>
            <p>Genre: @concert.Genre.ToString()</p>
        </article>
    }
</section>