TicketSystem/TicketSystem.Web/Areas/Organizer/Models/Concerts/CreateConcertViewModel.cs
using System.Collections.Generic;
using TicketSystem.Services.Organizer.Models;

namespace TicketSystem.Web.Areas.Organizer.Models.Concerts
{
    public class CreateConcertViewModel
    {
        public CreateConcertServiceModel ConcertServiceModel { get; set; }

        public List<GetBandsServiceModel> Bands { get; set; }
    }
}

TicketSystem/TicketSystem.Web/Areas/Organizer/Controllers/OrganizerBaseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TicketSystem.Common.Contstants;

namespace TicketSystem.Web.Areas.Organizer.Controllers
{
    [ Authorize( Roles = WebConstants.AdminRole + "," + WebConstants.OrganizerRole ) ]
    [ Area( WebConstants.OrganizerArea ) ]
    public abstract class OrganizerBaseController : Controller
    {
    }
}

TicketSystem/TicketSystem.Web/Areas/Organizer/Controllers/OrganizerController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TicketSystem.Services.Organizer.Contracts;
using TicketSystem.Services.Organizer.Models;
using TicketSystem.Web.Areas.Organizer.Models.Concerts;
using TicketSystem.Web.Extensions;

namespace TicketSystem.Web.Areas.Organizer.Controllers
{
    public class OrganizerController : OrganizerBaseController
    {
        private readonly IOrganizerService organizerService;

        public OrganizerController( IOrganizerService organizerService )
        {
            this.organizerService = organizerService;
        }

        [Route( "organizer/" )]
        public async Task< IActionResult > Index()
        {
            var concerts = await this.organizerService.AllAsync();

            return this.View( concerts );
        }

        [Route( "organizer/create" )]
        public async Task< IActionResult > Create()
        {
            var bands = await this.organizerService.BandsAsync();

            return this.View( new CreateConcertViewModel { Bands = bands } );
        }

        [ HttpPost ]
        [Route( "organizer/create" )]
        public async Task< IActionResult > Create( CreateConcertViewModel concertModel )
        {
            if ( concertModel.ConcertServiceModel.StartDate > concertModel.ConcertServiceModel.EndDate )
            {
                this.TempData.AddErrorMessage( "Start Date is after End Date!" );
                this.ModelState.AddModelError( "", "Start Date is after End Date!" );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.View( new CreateConcertViewModel
                {
                    Bands = await this.organizerService.BandsAsync(),
                    ConcertServiceModel = concertModel.ConcertServiceModel
                } );
            }

            var success = await this.organizerService.CreateAsync( concertModel.ConcertServiceModel );

            if ( !success )
            {
                return this.BadRequest();
            }

            this.TempData.AddSuccessMessage( $"Successfuly added '{concertModel.ConcertServiceModel.Name}' concert" );
            return this.RedirectToAction( nameof( this.Index ) );
        }

        [Route( "organizer/edit/{id}" )]
        public async Task< IActionResult > Edit( int id )
        {
            var concert = await this.organizerService.GetForEditAsync( id );

            return this.View( concert );
        }

        [ HttpPost ]
        [Route( "organizer/edit/{id}" )]
        public async Task< IActionResult > Edit( int id, EditConcertServiceModel editConcert )
        {
            if ( editConcert.StartDate > editConcert.EndDate )
            {
                this.ModelState.AddModelError( "", "Start Date is after End Date!" );
            }

            if ( !this.ModelState.IsValid )
            {
                return this.View( editConcert );
            }

            var success = await this.organizerService.EditAsync( id, editConcert );

            if ( !success )
            {
                return this.BadRequest();
            }

            return this.RedirectToAction( nameof( this.Index ) );
        }

        [Route( "organizer/delete/{id}" )]
        public async Task< IActionResult > Delete( int id )
        {
            if ( id <= 0 )
            {
                return this.BadRequest();
            }

            var success = await this.organizerService.Delete( id );

            if ( success )
            {
                return this.RedirectToAction( nameof( this.Index ) );
            }

            return this.BadRequest();
        }
    }
}

TicketSystem/TicketSystem.Web/Areas/Organizer/Views/Organizer/AddBands.cshtml
@model IEnumerable<GetBandsServiceModel   >

@{
    ViewBag.Title = "Add Bands";
    Layout = "_Layout";
}

<h2>@(this.ViewData[ "Title" ])</h2>

<div class="row ">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="BandId">Band</label>
                <select class="form-control Sharp" asp-for="BandId">
                    <option disabled selected>Select Band...</option>
                    @foreach ( var band in this.Model.Bands )
                    {
                        <optgroup label="@band.Genre">
                            <option value="@band.Id">@band.Name</option>
                        </optgroup>
                    }
                </select>
                <span asp-validation-for="@(this.Model.BandId)" class="text-danger"></span>
            </div>
            <input type="submit" class="btn btn-custom Sharp"/>
        </form>
    </div>
    <div class="col-md-3"></div>
</div>

@section Scripts {
    @await Html.PartialAsync( "_ValidationScriptsPartial" )
}

TicketSystem/TicketSystem.Web/Areas/Organizer/Views/Organizer/Create.cshtml
@model  CreateConcertViewModel 

@{
    ViewBag.Title = "Create Concert";
    Layout = "_Layout";
}
<script>
    $("body").addClass("OrganizerCreateConcert adm");
</script>


<h2 class="text-center pt-5 mb-5">@(this.ViewData[ "Title" ])</h2>

<div class="row pb-5">
    <div class="col-6 offset-3">
        <form method="post" asp-controller="Organizer" asp-action="Create">
            <div class="form-group">
                <label asp-for="@(this.Model.ConcertServiceModel.PosterUrl)"></label>
                <input asp-for="@(this.Model.ConcertServiceModel.PosterUrl)" class="form-control Sharp" placeholder="Enter Song Name..."/>
                <span asp-validation-for="@(this.Model.ConcertServiceModel.PosterUrl)" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@(this.Model.ConcertServiceModel.Name)"></label>
                <input asp-for="@(this.Model.ConcertServiceModel.Name)" class="form-control Sharp" placeholder="Enter Song Name..."/>
                <span asp-validation-for="@(this.Model.ConcertServiceModel.Name)" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@(this.Model.ConcertServiceModel.Genre)">Genre (Hold Ctrl to select multiple)</label> 
                <select asp-for="@(this.Model.ConcertServiceModel.Genre)" class="form-control Sharp" multiple="multiple" style="height: 135px">
                    <option selected disabled>Select Genre...</option>
                    @foreach ( var enumValue in Enum.GetValues( typeof( Genre ) ).Cast< Genre >() )
                    {
                        <option value="@( ( int ) enumValue )">@enumValue</option>
                    }
                </select>
                <span asp-validation-for="@(this.Model.ConcertServiceModel.Genre)" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@(this.Model.ConcertServiceModel.Country)"></label>
                <input asp-for="@(this.Model.ConcertServiceModel.Country)" class="form-control Sharp" placeholder="Enter Song Name..."/>
                <span asp-validation-for="@(this.Model.ConcertServiceModel.Country)" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@(this.Model.ConcertServiceModel.City)"></label>
                <input asp-for="@(this.Model.ConcertServiceModel.City)" class="form-control Sharp" placeholder="Enter Song Name..."/>
                <span asp-validation-for="@(this.Model.ConcertServiceModel.City)" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@(this.Model.ConcertServiceModel.Location)"></label>
                <input asp-for="@(this.Model.ConcertServiceModel.Location)" class="form-control Sharp" placeholder="Enter Song Name..."/>
                <span asp-validation-for="@(this.Model.ConcertServiceModel.Location)" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="@(this.Model.ConcertServiceModel.StartDate)"></label>
                        <input asp-for="@(this.Model.ConcertServiceModel.StartDate)" class="form-control Sharp" placeholder="Enter Song Name..."/>
                        <span asp-validation-for="@(this.Model.ConcertServiceModel.StartDate)" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="@(this.Model.ConcertServiceModel.EndDate)"></label>
                        <input asp-for="@(this.Model.ConcertServiceModel.EndDate)" class="form-control Sharp" placeholder="Enter Song Name..."/>
                        <span asp-validation-for="@(this.Model.ConcertServiceModel.EndDate)" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="@(this.Model.ConcertServiceModel.TicketPrice)"></label>
                <input asp-for="@(this.Model.ConcertServiceModel.TicketPrice)" class="form-control Sharp" placeholder="Price of Tickets..."/>
                <span asp-validation-for="@(this.Model.ConcertServiceModel.TicketPrice)" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@(this.Model.ConcertServiceModel.MaxNumberOfTickets)"></label>
                <input asp-for="@(this.Model.ConcertServiceModel.MaxNumberOfTickets)" class="form-control Sharp" placeholder="Maximum Number of Tickets..."/>
                <span asp-validation-for="@(this.Model.ConcertServiceModel.MaxNumberOfTickets)" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@(this.Model.ConcertServiceModel.Bands)"></label>
                <select asp-for="@(this.Model.ConcertServiceModel.Bands)" class="form-control Sharp" style="height: 300px">
                    <option selected disabled>Select Bands...</option>
                    @foreach ( var band in this.Model.Bands )
                    {
                        <option value="@band.Id">@band.Name - @band.Genre</option>
                    }
                </select>
                <span asp-validation-for="@(this.Model.ConcertServiceModel.Bands)" class="text-danger"></span>
            </div>
            <input type="submit" value="Create Concert" class="btn btn-custom Sharp"/>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync( "_ValidationScriptsPartial" )
}

TicketSystem/TicketSystem.Web/Areas/Organizer/Views/Organizer/Edit.cshtml
@model  EditConcertServiceModel 

@{
    ViewBag.Title = $"Edit Concert - \"{this.Model.Name}\" ";
    Layout = "_Layout";
}
<script>
    $("body").addClass("OrganizerCreateConcert adm");
</script>
<h2 class="text-center pt-5 mb-5">@(this.ViewData["Title"])</h2>


<div class="row ">
    <div class="col-4 offset-4">
        <form method="post" class="py-2">
            <div class="form-group">
                <label asp-for="StartDate"></label>
                <input asp-for="StartDate" class="form-control Sharp" placeholder="Enter Song Name..."/>
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate"></label>
                <input asp-for="EndDate" class="form-control Sharp" placeholder="Enter the YouTube Id..."/>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxNumberOfTickets"></label>
                <input asp-for="MaxNumberOfTickets" class="form-control Sharp" placeholder="Enter the YouTube Id..."/>
                <span asp-validation-for="MaxNumberOfTickets" class="text-danger"></span>
            </div>
            <input type="submit" class="btn  btn-custom" value="Save Changes"/>
        </form>
    </div>
</div>

TicketSystem/TicketSystem.Web/Areas/Organizer/Views/Organizer/Index.cshtml
@model IEnumerable<ListAllConcertsServiceModel>

@{
    ViewBag.Title = "All Concerts";
    Layout = "_Layout";
}

<script>
    $("body").addClass("OrganizerCreateConcert adm");
    $("main").addClass("pb-1 px-0");
</script>

<h2 class="text-center pt-5 mb-5">@(this.ViewData[ "Title" ])</h2>

<table class="table table-responsive table-hover concert-index">
    <thead style="background: black">
        <tr>
            <th class="text-center">Id</th>
            <th class="text-center">Name</th>
            <th class="text-center">Genre</th>
            <th class="text-center">Country</th>
            <th class="text-center">City</th>
            <th class="text-center" width="13%">№ Bands</th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach ( var concert in this.Model )
        {
            <tr>
                <td style="background: black">@concert.Id</td>
                <td>@concert.Name</td>
                <td>@concert.Genre.ToString()</td>
                <td class="text-center">@concert.Country</td>
                <td class="text-center">@concert.City</td>
                <td class="text-center">@concert.NumberOfBandsPlaying</td>
                <td>
                    <div class="btn-group">
                        <a asp-area="Organizer" asp-controller="Organizer" asp-action="Edit" asp-route-id="@concert.Id" class="btn btn-warning Sharp">Edit</a>
                        <a asp-area="Organizer" asp-controller="Organizer" asp-action="Delete" asp-route-id="@concert.Id" class=" btn btn-danger Sharp">Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>