TicketSystem/TicketSystem.Web/Areas/Admin/Controllers/UsersAdminController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using TicketSystem.Data.Models;
using TicketSystem.Services.Admin.Contracts;
using TicketSystem.Web.Areas.Admin.Models.UsersViewModels;
using TicketSystem.Web.Extensions;

namespace TicketSystem.Web.Areas.Admin.Controllers
{
    public class UsersAdminController : BaseAdminController
    {
        private readonly IAdminUserService adminUserService;
        private readonly RoleManager< IdentityRole > roleManager;
        private readonly UserManager< User > userManager;

        public UsersAdminController( IAdminUserService adminUserService, RoleManager< IdentityRole > roleManager,
            UserManager< User > userManager )
        {
            this.adminUserService = adminUserService;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public async Task< IActionResult > Index()
        {
            var users = await this.adminUserService.All();
            var roles = await this.roleManager
                .Roles
                .Select( r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name
                } )
                .ToListAsync();

            return this.View( new UsersListingViewModel
            {
                Roles = roles,
                Users = users
            } );
        }

        public async Task< IActionResult > AddToRole( AddToRoleFormModel roleModel )
        {
            var roleExsists = await this.roleManager.RoleExistsAsync( roleModel.Role );
            var user = await this.userManager.FindByIdAsync( roleModel.UserId );
            var userExists = user != null;

            if ( !roleExsists || !userExists )
            {
                this.ModelState.AddModelError( String.Empty, "Invalid identity details." );
            }

            if ( !this.ModelState.IsValid )
            {
                this.TempData.AddErrorMessage( "Failed to add user to role." );

                return this.RedirectToAction( nameof( this.Index ) );
            }

            await this.userManager.AddToRoleAsync( user, roleModel.Role );

            this.TempData.AddSuccessMessage( $"Successfuly added '{user.Name}' to '{roleModel.Role}' Role." );

            return this.RedirectToAction( nameof( this.Index ) );
        }
    }
}

TicketSystem/TicketSystem.Web/Areas/Admin/Views/UsersAdmin/AdminPage.cshtml
@{
    ViewBag.Title = "Administration";
    Layout = "_Layout";
}

<h1 class="text-center adm-pnl-hg">Administration</h1>

<section class="row">
    
    <article class="col-lg-4 text-center">
        <h4 class="adm-pnl-hg">Songs</h4>
        <div>
            <a class="adm-pnl-lk" asp-area="Admin" asp-controller="SongsAdmin" asp-action="Index">All Songs</a>
            <a class="adm-pnl-lk" asp-area="Admin" asp-controller="SongsAdmin" asp-action="Create">Create Song</a>
            <a class="adm-pnl-lk" asp-area="Admin" asp-controller="SongsAdmin" asp-action="CreateAlbum">Create Album</a>
            <a class="adm-pnl-lk" asp-area="Admin" asp-controller="BandsAdmin" asp-action="Create">Create Band</a>
        </div>
    </article>

    <article class="col-lg-4 text-center">
        <h4 class="adm-pnl-hg">Concerts</h4>
        <div>
            <a asp-area="Organizer" class="adm-pnl-lk" asp-controller="Organizer" asp-action="Create">Create Concert</a>
            <a asp-area="Organizer" class="adm-pnl-lk" asp-controller="Organizer" asp-action="Index">All Concerts</a>
        </div>                                               
    </article>                                              

    <article class="col-lg-4 text-center">
        <h4 class="adm-pnl-hg">Users</h4>
        <a asp-area="Admin" class="adm-pnl-lk" asp-controller="UsersAdmin" asp-action="Index">Manage Users</a>
    </article>
</section>

<script>
    $("body").addClass("admin-panel");
    $("main").attr("id","container");
</script>

TicketSystem/TicketSystem.Web/Areas/Admin/Views/UsersAdmin/Index.cshtml
@model  UsersListingViewModel 

@{
    ViewBag.Title = "All Users";
    Layout = "_Layout";
}

<script>
    $("body").addClass("ManageUsersAdmin adm");
    $("main").addClass("pb-1");
</script>

<h2 class="text-center pt-5 mb-5">@(this.ViewData[ "Title" ])</h2>

<table class="table table-hover AllSongsAdminTable">
    <thead>
    <tr>
        <th>UserName</th>
        <th>Name</th>
        <th>Email</th>
        <th>Roles</th>
    </tr>
    </thead>
    <tbody>
    @foreach ( var user in this.Model.Users )
    {
        <tr>
            <td>@user.UserName</td>
            <td>@user.Name</td>
            <td>@user.Email</td>
            <td>
                <form asp-controller="UsersAdmin" asp-action="AddToRole" method="post">
                    <div class="row">
                        <div class="col-md-8">
                            <input type="hidden" name="UserId" value="@user.Id"/>
                            <select name="Role" asp-items="this.Model.Roles" class="form-control Sharp"></select>
                        </div>
                        <div class="col-md-4">
                            <input class="btn btn-sm btn-success Sharp" type="submit" value="Add To Role"/>
                        </div>
                    </div>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>

@section Scripts {
    @await Html.PartialAsync( "_ValidationScriptsPartial" )
}